[manipulators]
reloadable = true
order = 0

[package]
version = "1.1.0"
category = "Simulation"
title = "Asimov Manipulators"
description = "Manipulators"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "manipulators"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.surface_gripper" = {}

[[python.module]]
name = "omni.asimov.manipulators"

[[python.module]]
name = "omni.asimov.manipulators.tests"
